services:
  mysql-training-mysql:
    container_name: mysql-training-mysql
    build:
      context: mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    command: mysqld --sql_mode="" --max_allowed_packet=16777216
    ulimits:
      nofile:
        # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
        soft: 1048576
        hard: 1048576
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    platform: linux/x86_64
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/dumps:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=demo
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  mysql-training-adminer:
    container_name: mysql-training-adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql-training-mysql
    links:
      - mysql-training-mysql
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
